package problem2;

/*
Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.
 */
public class Problem2 {

    public static void main(String[] args) {
        int oldNum = 1;
        int newNum = 2;
        int newTemp = 0;
        int sum = 0;

        for (; oldNum < 4_000_000;) {
            if (oldNum % 2 == 0) {
                sum += oldNum;
            }

            newTemp = oldNum + newNum;
            oldNum = newNum;
            newNum = newTemp;

        }
        System.out.println("sum is " + sum);
    }

}
